# Generated by Django 4.2 on 2023-05-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sciedit',
            fields=[
                ('seid', models.BigAutoField(primary_key=True, serialize=False)),
                ('issn', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('spid', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('dat', models.DateField()),
                ('seid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sciedit')),
            ],
        ),
        migrations.CreateModel(
            name='Quart',
            fields=[
                ('qid', models.BigAutoField(primary_key=True, serialize=False)),
                ('current_quartile', models.CharField(choices=[('K1', 'K1'), ('K2', 'K2'), ('K3', 'K3'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('db', models.CharField(choices=[('Scopus', 'Scopus'), ('WoS', 'WoS'), ('РИНЦ', 'РИНЦ'), ('ВАК', 'ВАК')], max_length=100)),
                ('year', models.IntegerField()),
                ('seid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sciedit')),
            ],
        ),
        migrations.CreateModel(
            name='Iff',
            fields=[
                ('ifid', models.BigAutoField(primary_key=True, serialize=False)),
                ('if_value', models.DecimalField(decimal_places=3, max_digits=7)),
                ('db', models.CharField(choices=[('Scopus', 'Scopus'), ('WoS', 'WoS'), ('РИНЦ', 'РИНЦ'), ('ВАК', 'ВАК')], max_length=100)),
                ('year', models.IntegerField()),
                ('seid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sciedit')),
            ],
        ),
    ]
