# Generated by Django 4.2 on 2023-05-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciedit',
            name='issn',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
