# Generated by Django 4.2 on 2023-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iff',
            name='db',
            field=models.CharField(choices=[('Scopus', 'Scopus'), ('WoS', 'WoS'), ('РИНЦ', 'РИНЦ'), ('ВАК', 'ВАК')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iff',
            name='if_value',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='iff',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quart',
            name='current_quartile',
            field=models.CharField(choices=[('K1', 'K1'), ('K2', 'K2'), ('K3', 'K3'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='quart',
            name='db',
            field=models.CharField(choices=[('Scopus', 'Scopus'), ('WoS', 'WoS'), ('РИНЦ', 'РИНЦ'), ('ВАК', 'ВАК')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quart',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sciedit',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='dat',
            field=models.DateField(null=True),
        ),
    ]
