# Generated by Django 4.2 on 2023-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_iff_db_alter_iff_if_value_alter_iff_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
