# Generated by Django 4.2 on 2023-06-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_specialty_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciedit',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
